name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      pull-requests: read
    outputs:
      src: ${{ steps.filter.outputs.src }}
      src-extra: ${{ steps.filter.outputs.src-extra }}
      docker: ${{ steps.filter.outputs.docker }}
      exceptions: ${{ steps.filter.outputs.exceptions }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup path filters
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            exceptions:
              - 'flatpak_builder_lint/staticfiles/exceptions.json'
            src:
              - '.github/**'
              - 'docker/**'
              - 'flatpak_builder_lint/!(staticfiles)/**'
              - 'tests/**'
              - 'utils/**'
              - 'poetry.lock'
              - 'pyproject.toml'
            src-extra:
              - 'flatpak_builder_lint/staticfiles/flatpak-manifest.schema.json'
              - 'flatpak_builder_lint/staticfiles/*.py'
            docker:
              - '.github/**'
              - 'docker/**'
              - 'flatpak_builder_lint/!(staticfiles)/**'
              - 'poetry.lock'
              - 'pyproject.toml'

  exceptions:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: changes
    if: ${{ needs.changes.outputs.exceptions == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Validate exceptions.json
        run: python3 utils/validator.py

  docker-call:
    permissions:
      packages: write
    needs:
      - changes
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
    uses: ./.github/workflows/docker.yml
    secrets: inherit
