name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master
    paths-ignore:
      - 'flatpak_builder_lint/staticfiles/exceptions.json'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder curl dbus-daemon libgirepository1.0-dev

      - name: Allow file:// clones with git>=2.38.1
        run: |
          git config --global protocol.file.allow always

      - name: Build and test org.flatpak.Builder
        run: |
          mkdir -p build && cd build
          git clone --depth=1 --branch master --recursive --single-branch https://github.com/flathub/org.flatpak.Builder.git
          python3 ../docker/rewrite-manifest.py && cd org.flatpak.Builder
          rm -v flatpak-builder-lint-deps.json && cp -v ../../docker/flatpak-builder-lint-deps.json .
          flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          flatpak-builder --verbose --user --force-clean --repo=repo \
            --install-deps-from=flathub --default-branch=localtest --ccache \
            --install builddir org.flatpak.Builder.json
          flatpak run org.flatpak.Builder//localtest --version

      - name: Sanity check the linter
        run: |
          cd build/org.flatpak.Builder
          flatpak run --command=flatpak-builder-lint org.flatpak.Builder//localtest --exceptions manifest org.flatpak.Builder.json
          flatpak run --command=flatpak-builder-lint org.flatpak.Builder//localtest --exceptions builddir builddir
          flatpak run --command=flatpak-builder-lint org.flatpak.Builder//localtest --exceptions repo repo

      - name: Set up appstreamcli
        run: |
          echo '#!/bin/sh' > /usr/local/bin/appstreamcli
          echo "exec dbus-run-session flatpak run --branch=localtest --command=appstreamcli org.flatpak.Builder \${@}" >> /usr/local/bin/appstreamcli
          chmod +x /usr/local/bin/appstreamcli
          appstreamcli --version

      - name: Setup Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          sudo ln -s /github/home/.local/bin/poetry /usr/bin/poetry

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        run: |
          poetry install

      - name: Check module sort order
        run: poetry run ruff check --select I flatpak_builder_lint

      - name: Check code formatting
        run: poetry run black --check flatpak_builder_lint

      - name: Check code errors
        run: poetry run flake8p flatpak_builder_lint

      - name: Check python types
        run: poetry run mypy flatpak_builder_lint

      - name: Run test suite
        run: poetry run pytest -v tests

      - name: Validate exceptions.json
        run: python3 validator.py flatpak_builder_lint/staticfiles/exceptions.json
