name: Docker

on:
  push:
    branches:
      - master
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache flatpak build
        uses: actions/cache@v3
        with:
          path: docker/.flatpak-builder
          key: fb-${{ matrix.platform }}-${{ hashFiles('poetry.lock') }}

      - name: Build flatpak-builder-lint
        run: |
          cd docker
          bash -x ./build.sh ${{ matrix.platform }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: docker
          file: docker/Dockerfile
          platforms: linux/${{ matrix.platform }}
          push: ${{ github.event_name != 'pull_request' }}
          provenance: false
          tags: |
            ghcr.io/flathub-infra/flatpak-builder-lint:${{ github.sha }}-${{ matrix.platform }}
            ghcr.io/flathub-infra/flatpak-builder-lint:latest-${{ matrix.platform }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=ssh://git@github.com:${{ github.repository }}.git
            org.opencontainers.image.url=https://github.com/${{ github.repository }}

      - name: Login to ghcr.io using Flathub credentials
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.FLATHUB_ORG_USER }}
          password: ${{ secrets.FLATHUB_ORG_TOKEN }}

      - name: Build and push Docker image to the old location
        uses: docker/build-push-action@v5
        with:
          context: docker
          file: docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          provenance: false
          tags: |
            ghcr.io/flathub/flatpak-builder-lint:${{ github.sha }}-${{ matrix.platform }}
            ghcr.io/flathub/flatpak-builder-lint:latest-${{ matrix.platform }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=ssh://git@github.com:${{ github.repository }}.git
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  docker-manifest:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    needs:
      - docker
    permissions:
      packages: write
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest
        run: |
          docker manifest create \
            ghcr.io/flathub-infra/flatpak-builder-lint:${{ github.sha }} \
            --amend ghcr.io/flathub-infra/flatpak-builder-lint:${{ github.sha }}-amd64 \
            --amend ghcr.io/flathub-infra/flatpak-builder-lint:${{ github.sha }}-arm64

          docker manifest push ghcr.io/flathub-infra/flatpak-builder-lint:${{ github.sha }}

          docker manifest create \
            ghcr.io/flathub-infra/flatpak-builder-lint:latest \
            --amend ghcr.io/flathub-infra/flatpak-builder-lint:${{ github.sha }}-amd64 \
            --amend ghcr.io/flathub-infra/flatpak-builder-lint:${{ github.sha }}-arm64

          docker manifest push ghcr.io/flathub-infra/flatpak-builder-lint:latest

      - name: Login to ghcr.io using Flathub credentials
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.FLATHUB_ORG_USER }}
          password: ${{ secrets.FLATHUB_ORG_TOKEN }}

      - name: Push manifest to the old location
        run: |
          docker manifest create \
            ghcr.io/flathub/flatpak-builder-lint:${{ github.sha }} \
            --amend ghcr.io/flathub-infra/flatpak-builder-lint:${{ github.sha }}-amd64 \
            --amend ghcr.io/flathub-infra/flatpak-builder-lint:${{ github.sha }}-arm64

          docker manifest push ghcr.io/flathub/flatpak-builder-lint:${{ github.sha }}

          docker manifest create \
            ghcr.io/flathub/flatpak-builder-lint:latest \
            --amend ghcr.io/flathub-infra/flatpak-builder-lint:${{ github.sha }}-amd64 \
            --amend ghcr.io/flathub-infra/flatpak-builder-lint:${{ github.sha }}-arm64

          docker manifest push ghcr.io/flathub/flatpak-builder-lint:latest
