name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      packages: write
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      - name: Test
        run: echo "Foo"

  docker-manifest:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs:
      - docker
    permissions:
      packages: write
    steps:
      - name: Test
        run: echo "Foo"
